name: polarfire-kernel
adopt-info: kernel
type: kernel
build-base: core22
summary: An Ubuntu Core kernel for the Microchip Polarfire SoC Icicle
description: |
  This snap provides the kernel, modules, firmware, and initrd required to
  create an Ubuntu Core image for the RISC-V Microchip Polarfire Icicle.

  The kernel and initrd are provided as a singular FIT image file.

architectures:
  - build-on:  [amd64, riscv64]
    build-for: [riscv64]

grade: stable
confinement: strict

license: "GPL-2.0 AND GPL-3.0 AND CC-BY-SA-4.0"
issues: https://github.com/canonical/iot-field-kernel-snap/issues
website: https://github.com/canonical/iot-field-kernel-snap/tree/22/polarfire-icicle

package-repositories:
  - type: apt
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    components: [main]
    suites: [jammy]
    key-id: 110E21D8B0E2A1F0243AF6820856F197B892ACEA
    url: https://ppa.launchpadcontent.net/canonical-kernel-team/ppa/ubuntu

parts:
  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware:all
      - nouveau-firmware:all
      - wireless-regdb:all
    organize:
      lib/firmware: firmware/
    stage:
    # Remove firmware files for things that will never be needed
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/qcom
      - -firmware/netronome
      - -firmware/intel
      - -firmware/liquidio
      - -firmware/i915
      - -firmware/brcm
      - -firmware/qed

  kernel:
    plugin: nil
    stage-packages:
      - linux-image-generic:${CRAFT_ARCH_BUILD_FOR}
    override-build: |
      craftctl default

      kver="$(basename "${CRAFT_PART_INSTALL}/lib/modules/"*)"

      depmod -a -b ${CRAFT_PART_INSTALL} ${kver}

      craftctl set version="$(apt info linux-image-generic:${CRAFT_ARCH_BUILD_FOR} | grep Version: | cut -f2 -d\ )"
    organize:
      boot/vmlinuz-*: Image
      lib/modules: modules/
      lib/firmware/*/device-tree: dtbs/
    stage:
      - Image
      - modules/
      - dtbs/device-tree/microchip/mpfs-icicle-kit.dtb
    prime:
      - modules/

  initrd:
    plugin: initrd
    after: [kernel, firmware]
    initrd-build-efi-image: false
    build-snaps: [core22/latest/stable]
    prime:
      - -*

  fit-image:
    after: [kernel, initrd]
    plugin: dump
    source: fit-image/
    build-packages: [device-tree-compiler, u-boot-tools]
    override-stage: |
      craftctl default

      mkimage \
        -f "${CRAFT_STAGE}/fitImage-${CRAFT_ARCH_BUILD_FOR}.its" \
        "${CRAFT_PRIME}/kernel.img"
    prime:
      - -*
