name: nezha-kernel
type: kernel
build-base: core24
adopt-info: kernel
summary: An Ubuntu Core kernel for the RISC-V AllWinner Nezha
description: |
  This snap provides the kernel, modules, firmware, and initrd required to
  create an Ubuntu Core image for the RISC-V AllWinner Nezha.

  The kernel and initrd are provided as a single universal kernel image file
  which is then booted by the managed assets created and owned by snapd.
  Generally, this snap would also provide the device tree files for the target
  hardware. However, in this case, that device tree is provided by the u-boot
  binary in our gadget snap. If we needed it here, we could likewise add that
  file to our UKI.

  ** Note that the license information for this snap is incomplete **
  Do your due diligence to ensure compliance with the licenses of the contents of this snap.

  This snapcraft.yaml is licensed under CC-BY-SA-4.0

  You can find any and all licenses for the contents of this snap at the following locations:

  kernel:             https://git.launchpad.net/~canonical-kernel/ubuntu/+source/linux-riscv/+git/noble/tree/?h=allwinner-next
  linux-firmware:     https://git.launchpad.net/ubuntu/+source/linux-firmware/tree/?h=applied/ubuntu/noble
  rtl8723ds:          https://git.launchpad.net/ubuntu/+source/licheerv-rtl8723ds-dkms/tree/
  rtl8723ds upstream: https://github.com/lwfinger/rtl8723ds

  Additional licenses can also be found within this snap in the licenses/ top-level directory.

# core24 is currently a devel-only base.
grade: devel
confinement: strict

license: "GPL-2.0 AND GPL-3.0 AND CC-BY-SA-4.0"
website: https://github.com/canonical/iot-field-kernel-snap
issues: https://github.com/canonical/iot-field-kernel-snap/issues

# We cannot cross-build the kernel snap at this time. To do so, we would have to
# hand-craft an initrd. While not impossible, it is a little too demanding for
# our purposes at this time.
platforms:
  riscv64:
    build-on:  [amd64, riscv64]
    build-for: [riscv64]

parts:
  # Provide the kernel.
  # Trimming any modules we know a priori to not be needed by the target device
  # can marginally reduce kernel snap size.
  kernel:
    plugin: nil
    source: https://git.launchpad.net/canonical-kernel-snaps
    source-depth: 1
    source-type: git
    stage-packages:
      - linux-allwinner:${CRAFT_ARCH_BUILD_FOR}
      - linux-firmware:${CRAFT_ARCH_BUILD_FOR}
      - wireless-regdb
    override-build: |
      craftctl default

      kver="$(basename "${CRAFT_PART_INSTALL}/lib/modules/"*)"

      # Set the version of the snap to match the kernel version.
      craftctl set version="$kver"

      # Create the module information tree.
      depmod -a -b "${CRAFT_PART_INSTALL}" "$kver"

      [ ! -d "${CRAFT_PART_INSTALL}/lib/modules" ] || {
        mv -f "${CRAFT_PART_INSTALL}/lib/modules" "${CRAFT_PART_INSTALL}"
      }
      [ ! -d "${CRAFT_PART_INSTALL}/lib/firmware" ] || {
        mv -f "${CRAFT_PART_INSTALL}/lib/firmware" "${CRAFT_PART_INSTALL}"
      }

      mv -f "${CRAFT_PART_INSTALL}/boot/"* "${CRAFT_PART_INSTALL}"

      # Ubuntu Core expects modules/ to be a top-level directory in the snap,
      # but we must also maintain compatibility with things which expect it to
      # be in lib/modules/
      ln -sf ../modules  "${CRAFT_PART_INSTALL}/lib/modules"
      ln -sf ../firmware "${CRAFT_PART_INSTALL}/lib/firmware"

      "${CRAFT_PART_SRC}/trim-firmware" "${CRAFT_PART_INSTALL}"
    organize:
      vmlinuz-*: kernel.img
    stage:
      - config-*
      - firmware/
      - kernel.img
      - lib/firmware
      - lib/modules
      - modules/
      - System.map*
    prime:
      - -kernel.img

  # Provide the initrd for Ubuntu Core.
  # The initrd includes important things such as snap-bootstrap which
  # orchestrates the entire Ubuntu Core installation process. The documentation
  # for this tool can be found here:
  # https://github.com/snapcore/snapd/blob/master/cmd/snap-bootstrap/README.md
  initrd:
    plugin: initrd
    after: [kernel]
    initrd-build-efi-image: true
    initrd-configured-modules: [nls_iso8859-1, sunxi-mmc]
    build-snaps: [core24/latest/stable]
