---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Isaac True

name: odroid-hc4-kernel
summary: A kernel for the ODROID HC4 platform for use with Ubuntu Core 22
description: |
  A kernel for the ODROID HC4 platform for use with Ubuntu Core 22

adopt-info: kernel
build-base: core22
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on: [arm64]
    run-on: arm64

parts:
  kernel:
    plugin: nil
    stage-snaps:
      - pc-kernel/22/stable
