---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Isaac True
name: odroid-hc4-kernel
adopt-info: kernel
type: kernel
build-base: core22
summary: An Ubuntu Core kernel for the ARM64 ODROID HC4
description: |
  This snap provides the kernel, modules, firmware, and initrd required to
  create an Ubuntu Core image for the ARM64 ODROID HC4.

  The kernel and initrd are provided as a single FIT image file.

  ** Note that the license information for this snap is incomplete **
  Do your due diligence to ensure compliance with the licenses of the contents of this snap.

  This snapcraft.yaml is licensed under CC-BY-SA-4.0

grade: stable
confinement: strict

license: "GPL-2.0 AND GPL-3.0 AND CC-BY-SA-4.0"
issues: https://github.com/canonical/iot-field-kernel-snap/issues
website: https://github.com/canonical/iot-field-kernel-snap/tree/22/odroid-hc4

architectures:
  - build-on:  [arm64, amd64]
    build-for: [arm64]

package-repositories:
  - type: apt
    components: [main]
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    suites: [jammy, jammy-security, jammy-updates]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports

parts:
  kernel:
    plugin: nil
    stage-packages:
      - linux-generic:${CRAFT_ARCH_BUILD_FOR}
    override-build: |
      craftctl default

      craftctl set version="$(apt info linux-generic:${CRAFT_ARCH_BUILD_FOR} | grep Version: | cut -f2 -d\ )"

      kver="$(basename ${CRAFT_PART_INSTALL}/boot/vmlinuz-* | cut -f2- -d-)"

      depmod -ab "${CRAFT_PART_INSTALL}" "${kver}"
    organize:
      lib/modules: modules/
      "boot/vmlinuz-*": kernel.img
      "lib/firmware/*/device-tree/amlogic/*": dtbs/
    stage:
      - dtbs/meson-sm1-odroid-hc4.dtb
      - kernel.img
      - modules/
    prime:
      - dtbs/meson-sm1-odroid-hc4.dtb
      - kernel.img
      - modules/

  firmware:
    plugin: nil
    stage-packages: [linux-firmware]
    organize:
      "lib/firmware": firmware
    prime:
      - firmware/
      # Remove large unneeded firmware files
      - -firmware/amdgpu/
      - -firmware/asihpi/
      - -firmware/ath10k/
      - -firmware/ath11k/
      - -firmware/ath12k/
      - -firmware/bnx2x/
      - -firmware/brcm/
      - -firmware/cxgb4/
      - -firmware/cypress/
      - -firmware/dpaa2/
      - -firmware/i915/
      - -firmware/intel/
      - -firmware/iwlwifi-*
      - -firmware/libertas/
      - -firmware/liquidio/
      - -firmware/mediatek/
      - -firmware/mellanox/
      - -firmware/mrvl/
      - -firmware/netronome/
      - -firmware/nvidia/
      - -firmware/qcom/
      - -firmware/qed/
      - -firmware/radeon/

  initrd:
    plugin: initrd
    after: [kernel, firmware]
    initrd-build-efi-image: false
    build-snaps: [core22/latest/stable]
    prime:
      - -initrd.img-*
      - -kernel.efi-*
