---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Isaac True

name: odroid-hc4-kernel
summary: A kernel for the ODROID HC4 platform for use with Ubuntu Core 20
description: |
  A kernel for the ODROID HC4 platform for use with Ubuntu Core 20

adopt-info: kernel
build-base: core20
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on:
      - amd64
      - arm64
    run-on: arm64

parts:
  # Normally we could use the stock HWE kernel, but it's missing CONFIG_PCI_MESON
  # for the PCIE driver, so we have to compile the whole kernel.
  kernel:
    plugin: x-kernel
    after: 
      - firmware
    source: https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/focal
    source-branch: hwe-5.15
    source-depth: 1
    source-type: git
    kernel-compiler: ${SNAPCRAFT_ARCH_TRIPLET}-gcc
    kernel-with-firmware: false
    kernel-image-target: Image
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    kconfigflavour: generic
    kernel-enable-zfs-support: true
    kernel-device-trees:
      - amlogic/meson-sm1-odroid-hc4
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    kconfigs:
      - CONFIG_SYSTEM_REVOCATION_KEYS=""
      - CONFIG_SYSTEM_TRUSTED_KEYS=""
      - CONFIG_DEBUG_INFO_BTF=n
      - CONFIG_DEBUG_INFO=n
      - CONFIG_PCI_MESON=m
      # Drivers required to boot
      - CONFIG_I2C_MESON=y
      - CONFIG_PWM_MESON=y
      - CONFIG_MMC_MESON_GX=y
      - CONFIG_REGULATOR_GPIO=y
      - CONFIG_REGULATOR_FIXED_VOLTAGE=y
      - CONFIG_NLS_ISO8859_1=y
      # Disable unneeded modules
      - CONFIG_DRM_RADEON=n
      - CONFIG_DRM_NOUVEAU=n
      - CONFIG_DRM_VIRTIO_GPU=n
      - CONFIG_DRM_AMDGPU=n
      - CONFIG_DRM_MXSFB=n
      - CONFIG_DRM_QXL=n
      - CONFIG_DRM_MGAG200=n
      - CONFIG_DRM_VKMS=n
      - CONFIG_DRM_BOCHS=n
      - CONFIG_DRM_ARCPGU=n
      - CONFIG_DRM_GM12U320=n
      - CONFIG_DRM_CIRRUS_QEMU=n
    override-pull: |
      snapcraftctl pull
      # This file is missing from the hwe-5.15 branch for some reason
      touch ${SNAPCRAFT_PART_SRC}/debian.hwe-5.15/config/config.common.ports
    override-build: |
      snapcraftctl build
      # Extract version from Debian changelog
      snapcraftctl set-version $(head -n1 ${SNAPCRAFT_PART_SRC}/debian.hwe-5.15/changelog | cut -f2 -d\( | cut -f1 -d\))
    build-packages:
      - dpkg-dev
      - flex
      - bison
      - binutils
      - libssl-dev
      - libfdt-dev
      - cpio
      - binutils-${SNAPCRAFT_ARCH_TRIPLET}
      - device-tree-compiler
      - libelf-dev
      - u-boot-tools
      - on arm64:
          - gcc
      - else:
          - gcc-${SNAPCRAFT_ARCH_TRIPLET}

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    stage:
      - -usr
    # Remove large firmware files that will never be needed
    prime:
      - -firmware/netronome
      - -firmware/intel
      - -firmware/amdgpu
      - -firmware/liquidio
      - -firmware/qcom
      - -firmware/mellanox
      - -firmware/radeon
      - -firmware/i915
    organize:
      lib/firmware: firmware
