---
# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (C) 2023 Isaac True
name: orange-pi-5plus-kernel
adopt-info: kernel
type: kernel
build-base: core22
summary: An Ubuntu Core kernel for the ARM64 Orange Pi 5+
description: |
  This snap provides the kernel, modules, firmware, and initrd required to
  create an Ubuntu Core image for the ARM64 Orange Pi 5+.

  The kernel and initrd are provided as a single FIT image file.

  ** Note that the license information for this snap is incomplete **
  Do your due diligence to ensure compliance with the licenses of the contents of this snap.

  The snapcraft.yaml and fit_arm64.its are licensed under CC-BY-SA-4.0
  A kernel for the Orange Pi 5+ for use with Ubuntu Core 22

grade: stable
confinement: strict

license: "GPL-2.0 AND GPL-3.0 AND CC-BY-SA-4.0"
issues: https://github.com/canonical/iot-field-kernel-snap/issues
website: https://github.com/canonical/iot-field-kernel-snap/tree/22/orangepi-5plus

architectures:
  - build-on:  [arm64, amd64]
    build-for: [arm64]

package-repositories:
  - type: apt
    components: [main]
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    suites: [jammy, jammy-updates, jammy-security]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports

parts:
  kernel:
    plugin: kernel
    source: http://git.launchpad.net/~itrue/ubuntu/+source/linux/+git/jammy
    source-branch: orange-pi-6.1-rk35xx-ubuntu
    source-depth: 1
    source-type: git
    kernel-kconfigflavour: "rk35xx"
    build-packages:
      - on arm64:
        - gcc-12
        - g++-12
      - on amd64:
        - gcc-12-${CRAFT_ARCH_TRIPLET_BUILD_FOR}
        - g++-12-${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    override-build: |
      # Complaints are made if gcc < 12
      for f in cc ++; do
        update-alternatives --install \
          "/usr/bin/${CRAFT_ARCH_TRIPLET_BUILD_FOR}-g${f}" "g${f}" \
          "/usr/bin/${CRAFT_ARCH_TRIPLET_BUILD_FOR}-g${f}-12" 10
      done

      craftctl default

      craftctl set version="$(head -n1 "${CRAFT_PART_SRC}/debian.rk35xx/changelog" | cut -f2 -d\( | cut -f1 -d\))"
    stage:
      - dtbs/
      - kernel.img
      - lib/
      - modules/
    prime:
      - -dtbs/
      - -kernel.img

  firmware:
    plugin: nil
    source: https://github.com/orangepi-xunlong/firmware.git
    source-type: git
    source-depth: 1
    stage-packages:
      - linux-firmware:all
      - wireless-regdb:all
    override-build: |
      # Overwrite any firmware files from OPi with the ones from linux-firmware
      # Need to do this here rather than in organize because it doesn't like
      # merging paths
      mkdir -p "${CRAFT_PART_INSTALL}/firmware"

      cp -rf "${CRAFT_PART_SRC}/"* "${CRAFT_PART_INSTALL}/firmware"
      cp -rf "${CRAFT_PART_INSTALL}/lib/firmware/"* \
        "${CRAFT_PART_INSTALL}/firmware/"

      rm -rf "${CRAFT_PART_INSTALL}/firmware/lib"
    stage:
      - firmware/
    prime:
      # Remove massive and unneeded firmware files
      - -firmware/amdgpu/
      - -firmware/ath11k/
      - -firmware/i915/
      - -firmware/intel/
      - -firmware/liquidio/
      - -firmware/mellanox/

  initrd:
    plugin: initrd
    after: [kernel, firmware]
    initrd-build-efi-image: false
    build-snaps: [core22/latest/stable]
    prime:
      - -*

  fit-image:
    after: [kernel, initrd]
    plugin: dump
    source: fit-image/
    build-packages: [u-boot-tools, device-tree-compiler]
    override-stage: |
      craftctl default

      mkimage \
        -f "${CRAFT_STAGE}/kernel_${CRAFT_ARCH_BUILD_FOR}.its" \
        "${CRAFT_PRIME}/kernel.img"
    prime:
      - -*
