---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Isaac True

name: iotdevice-odroid-hc4-kernel
summary: A kernel for the ODROID HC4 platform for use with Ubuntu Core 22
description: |
  A kernel for the ODROID HC4 platform for use with Ubuntu Core 22

adopt-info: kernel
build-base: core22
confinement: strict
type: kernel

architectures:
  - build-on: [arm64]
    build-for: arm64

parts:
  kernel:
    plugin: nil
    stage-snaps:
      - pc-kernel/22/stable
    override-build: |
      craftctl default
      craftctl set version=$(grep '^version:' ${CRAFT_PART_INSTALL}/snap.pc-kernel/manifest.yaml | cut -f2 -d\ )
      craftctl set grade=$(grep '^grade:' ${CRAFT_PART_INSTALL}/snap.pc-kernel/manifest.yaml | cut -f2 -d\ )
