---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Isaac True

name: iotdevice-odroid-hc4-kernel
summary: A kernel for the ODROID HC4 platform for use with Ubuntu Core 22
description: |
  A kernel for the ODROID HC4 platform for use with Ubuntu Core 22

adopt-info: kernel
build-base: core22
confinement: strict
type: kernel

architectures:
  - build-on: [arm64]
    build-for: arm64

parts:
  kernel:
    plugin: nil
    stage-snaps:
      - pc-kernel/22/stable
    override-build: |
      craftctl default
      craftctl set version=$(grep '^version:' ${CRAFT_PART_INSTALL}/snap.pc-kernel/manifest.yaml | cut -f2 -d\ )
      craftctl set grade=$(grep '^grade:' ${CRAFT_PART_INSTALL}/snap.pc-kernel/manifest.yaml | cut -f2 -d\ )
    prime:
      - -kernel.efi
      - -firmware/*/device-tree

  kernel-image:
    plugin: nil
    after: [kernel]
    build-packages:
      - binutils
    override-build: |
      objcopy ${CRAFT_STAGE}/kernel.efi --dump-section .linux=${CRAFT_PART_INSTALL}/kernel.img

  initrd:
    plugin: nil
    after: [kernel]
    build-packages:
      - binutils
      - zstd
      - cpio
      - kmod
    override-build: |
      objcopy ${CRAFT_STAGE}/kernel.efi --dump-section .initrd=${CRAFT_PART_BUILD}/initrd.img

      # Need to add more modules
      zstdcat ${CRAFT_PART_BUILD}/initrd.img | cpio -i
      rm ${CRAFT_PART_BUILD}/initrd.img

      for mod in \
          i2c-meson \
          meson-gx-mmc \
          pwm-meson \
          i2c-meson \
          nls_iso8859-1 \
          fixed \
          gpio-regulator \
          pci-meson \
        ; do
        MOD=$(find ${CRAFT_STAGE}/modules -name ${mod}.ko)
        install -Dm0644 ${MOD} -t $(dirname ${CRAFT_PART_BUILD}/lib/modules/$(echo ${MOD} | sed 's;^${CRAFT_STAGE}/modules/;;'))
      done

      depmod -b ${CRAFT_PART_BUILD} $(basename $(ls ${CRAFT_PART_BUILD}/lib/modules))

      # Recreate the initrd
      find ./ | cpio -o -H newc | zstd -vc > ${CRAFT_PART_INSTALL}/initrd.img

  dtb:
    plugin: nil
    after: [kernel]
    override-build: |
      install -Dm0644 ${CRAFT_STAGE}/firmware/*/device-tree/amlogic/meson-sm1-odroid-hc4.dtb \
        -t ${CRAFT_PART_INSTALL}/dtbs
