---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Isaac True

name: odroid-hc4-kernel
summary: A kernel for the ODROID HC4 platform for use with Ubuntu Core 22
description: |
  A kernel for the ODROID HC4 platform for use with Ubuntu Core 22

adopt-info: kernel
build-base: core22
confinement: strict
type: kernel

architectures:
  - build-on: [arm64]
    build-for: arm64

parts:
  kernel:
    plugin: nil
    stage-packages:
      - linux-generic:${CRAFT_TARGET_ARCH}
    override-build: |
      craftctl default
      KERNEL_VER="$(basename ${CRAFT_PART_INSTALL}/boot/vmlinuz-* | cut -f2- -d-)"
      craftctl set version="${KERNEL_VER}"
      craftctl set grade="stable"
      echo "${KERNEL_VER}" > "${CRAFT_PART_INSTALL}/.kernel_ver"

      depmod -a -b "${CRAFT_PART_INSTALL}" "${KERNEL_VER}"
    organize:
      "boot/vmlinuz-*": kernel.img
      "lib/modules": modules
      "lib/firmware/*/device-tree/amlogic": dtbs
    stage:
      - kernel.img
      - dtbs
      - modules
      - .kernel_ver
    prime:
      - kernel.img
      - dtbs
      - modules

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    organize:
      "lib/firmware": firmware
    prime:
      - firmware
      # Remove large unneeded firmware files
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/amdgpu
      - -firmware/qcom
      - -firmware/netronome
      - -firmware/intel
      - -firmware/i915
      - -firmware/mediatek
      - -firmware/qed
      - -firmware/liquidio
      - -firmware/dpaa2
      - -firmware/radeon

  # In order to support cross-compilation, we need to do a few tricks with
  # downloading the initramfs package for the target arch
  ubuntu-core-initramfs:
    plugin: nil
    override-pull: |
      apt-get download ubuntu-core-initramfs:riscv64
    override-build: |
      dpkg -x ubuntu-core-initramfs*_riscv64.deb \
        ${CRAFT_PART_INSTALL}

      # Extra initrd modules
      for mod in \
          i2c-meson \
          meson-gx-mmc \
          pwm-meson \
          i2c-meson \
          nls_iso8859-1 \
          fixed \
          gpio-regulator \
          pci-meson \
        ; do
        echo ${mod} >> \
          ${CRAFT_PART_INSTALL}/usr/lib/ubuntu-core-initramfs/modules/main/extra-modules.conf
      done
    organize:
      usr/lib/ubuntu-core-initramfs: ubuntu-core-initramfs
    prime:
      - -*

  initrd:
    plugin: nil
    after:
      - kernel
      - ubuntu-core-initramfs
      - firmware
    build-packages:
      # Use the native package to actually build the initrd
      - ubuntu-core-initramfs
    override-build: |
      KERNEL_VERSION=$(cat ${CRAFT_STAGE}/.kernel_ver)
      ubuntu-core-initramfs create-initrd \
        --kernelver=${KERNEL_VERSION} \
        --kerneldir=${CRAFT_STAGE}/modules/${KERNEL_VERSION} \
        --skeleton=${CRAFT_STAGE}/ubuntu-core-initramfs \
        --firmwaredir=${CRAFT_STAGE}/firmware \
        --output=${CRAFT_PART_INSTALL}/initrd.img
    organize:
      # Remove version suffix
      initrd.img*: initrd.img
    prime:
      - -*
