name: visionfive2-kernel
adopt-info: kernel
type: kernel
build-base: core24
summary: A StarFive VisionFive 2 board kernel for use with Ubuntu Core 24
description: |
  This snap provides the kernel, modules, firmware, and initrd required to
  create an Ubuntu Core image for the StarFive VisionFive 2.

  The kernel and initrd are provided as a single universal kernel image file
  which is then booted by the managed assets created and owned by snapd.
  Generally, this snap would also provide the device tree files for the target
  hardware. However, in this case, that device tree is provided by the u-boot
  binary in our gadget snap. If we needed it here, we could likewise add that
  file to our UKI.

  ** Note that the license information for this snap is incomplete **
  Do your due diligence to ensure compliance with the licenses of the contents of this snap.

  This snapcraft.yaml is licensed under CC-BY-SA-4.0

  You can find any and all licenses for the contents of this snap at the following locations:

  kernel:         https://git.launchpad.net/~canonical-kernel/ubuntu/+source/linux-riscv/+git/noble/tree/?h=allwinner-next
  linux-firmware: https://git.launchpad.net/ubuntu/+source/linux-firmware/tree/?h=applied/ubuntu/noble

  Additional licenses can also be found within this snap in the licenses/ top-level directory.

license: "GPL-2.0 AND GPL-3.0 AND CC-BY-SA-4.0"
website: https://github.com/canonical/iot-field-kernel-snap
issues: https://github.com/canonical/iot-field-kernel-snap/issues
source-code: https://github.com/canonical/iot-field-kernel-snap/tree/24-riscv64-visionfive2

grade: devel
confinement: strict

platforms:
  riscv64:
    build-on: [amd64, riscv64]
    build-for: [riscv64]

package-repositories:
  - type: apt
    components: [main, universe]
    architectures: [riscv64]
    suites: [noble, noble-security, noble-updates]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports

parts:
  # This can serve as an example for building the kernel from source
  kernel:
    plugin: kernel
    kernel-ubuntu-release-name: noble
    kernel-ubuntu-kconfigflavour: riscv
    kernel-ubuntu-abinumber: riscv-6.17-next
    kernel-kconfigs:
      - CONFIG_SYSTEM_TRUSTED_KEYS=""
      - CONFIG_SYSTEM_REVOCATION_KEYS=""
    stage-packages:
      - linux-firmware:${CRAFT_ARCH_BUILD_FOR}
      - wireless-regdb:all
    override-build: |
      craftctl default

      kver="$(basename "${CRAFT_PART_INSTALL}/lib/modules/"*)"

      # Set the version of the snap to match the kernel version.
      craftctl set version="${kver}"
    organize:
      dtbs/starfive: dtbs/
    stage:
      - System.map-*
      - config-*
      - dtbs/
      - firmware/
      - lib/firmware
      - lib/modules
      - modules/
      - kernel.img*
    prime:
      - dtbs/
      - firmware/
      - lib/firmware
      - lib/modules
      - modules/

  # Trimming any firmware we know a priori to not be needed by the target device
  # can reduce kernel snap size.
  trim-firmware:
    plugin: dump
    after: [kernel]
    source: https://git.launchpad.net/canonical-kernel-snaps
    source-depth: 1
    source-type: git
    stage:
      - trim-firmware
    override-prime: |
      craftctl default
      "${CRAFT_STAGE}/trim-firmware" "${CRAFT_PRIME}"
    prime:
      - -*

  # Make sure some important modules are in the initrd so the rootfs can be
  # mounted. Note that these could be optionally builtin to the kernel directly
  # as it is being build from source!
  initrd:
    after: [kernel, trim-firmware]
    plugin: initrd
    initrd-build-efi-image: true
    initrd-modules: [nls_iso8859-1, dw_mmc-starfive, dwmac_starfive]
    prime:
      - manifest-initramfs.yaml*
      - snapd-info

  fit-image:
    after: [kernel, initrd]
    plugin: dump
    source: fit-image/
    build-packages: [device-tree-compiler, u-boot-tools]
    override-stage: |
      craftctl default

      mkimage \
        -f "${CRAFT_STAGE}/kernel_${CRAFT_ARCH_BUILD_FOR}.its" \
        "${CRAFT_PRIME}/kernel.img"
    prime:
      - -*

  # Snapcraft does not handle kernel.yaml files for us like it does gadget.yaml :'(
  kernel-yaml:
    plugin: dump
    source: src/
    override-prime: |-
      install -Dm644 "${CRAFT_STAGE}/kernel.yaml" "${CRAFT_PRIME}/meta/kernel.yaml"
